# This file was generated by GoReleaser. DO NOT EDIT.
cask "golf-scanner" do
  name "golf-scanner"
  desc "Security scanner for MCP servers"
  homepage "https://github.com/golf-mcp/golf-scanner"
  version "0.1.0-rc.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "golf-scanner"

  on_macos do
    on_intel do
      url "https://github.com/golf-mcp/golf-scanner/releases/download/v#{version}/golf-scanner_#{version}_darwin_amd64.tar.gz"
      sha256 "1a82d6e089d43ccd0235811bbbe75033b51d33d66a43f4d4fe2af56677f3128e"
    end
    on_arm do
      url "https://github.com/golf-mcp/golf-scanner/releases/download/v#{version}/golf-scanner_#{version}_darwin_arm64.tar.gz"
      sha256 "806ddc1925d1de39bc253cb0cc6b9882697325b9b81a74232a282964abc72528"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/golf-mcp/golf-scanner/releases/download/v#{version}/golf-scanner_#{version}_linux_amd64.tar.gz"
      sha256 "7f4e7e254da72a75608933e72199519c0812d8225179d340bba77014765b63f4"
    end
    on_arm do
      url "https://github.com/golf-mcp/golf-scanner/releases/download/v#{version}/golf-scanner_#{version}_linux_arm64.tar.gz"
      sha256 "219c8eaab8abceab3291076016d08f0a1333139eee6bdfedd5c3af29b818164d"
    end
  end

  # No zap stanza required
end
