# This file was generated by GoReleaser. DO NOT EDIT.
cask "golf-scanner" do
  name "golf-scanner"
  desc "Security scanner for MCP servers"
  homepage "https://github.com/golf-mcp/golf-scanner"
  version "0.1.0-rc.3"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "golf-scanner"

  on_macos do
    on_intel do
      url "https://github.com/golf-mcp/golf-scanner/releases/download/v#{version}/golf-scanner_#{version}_darwin_amd64.tar.gz"
      sha256 "78a7c98ef8cf112ec71847f302d36582cc21ea3ac6a456ad7a03b96373a8ff72"
    end
    on_arm do
      url "https://github.com/golf-mcp/golf-scanner/releases/download/v#{version}/golf-scanner_#{version}_darwin_arm64.tar.gz"
      sha256 "ba660a910f3b7deebceb861c3f8135e00438f879de60c9d6e45aa04ed13fe49d"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/golf-mcp/golf-scanner/releases/download/v#{version}/golf-scanner_#{version}_linux_amd64.tar.gz"
      sha256 "424ebf1ace17532ffa307e882b38a83e89eaf9efe6f5c111234a7b739713f13d"
    end
    on_arm do
      url "https://github.com/golf-mcp/golf-scanner/releases/download/v#{version}/golf-scanner_#{version}_linux_arm64.tar.gz"
      sha256 "cf0dd2b1f27434d1ec50fe6d179883fbe1ec509eb257c2eb365f041bdc101e80"
    end
  end

  # No zap stanza required
end
